### ISSUE TITLE
Can't use the addon

### ISSUE THREAD

**Issue by FiFeX** [DxCx/plugin.video.wonderfulsubs#133]
Using the lastest version of kodi (18.6 I think).
Happens for like 2 weeks now,no matter the show.
I can enter the addon and use the search,but that's about it.
Here's the log:

> 
2020-03-19 11:31:41.840 T:11112   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.wonderfulsubs/search/code geass/1
2020-03-19 11:31:41.852 T:6528   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.wonderfulsubs/search/code geass/1) failed
2020-03-19 11:31:43.237 T:6528 WARNING: Repository add-on repository.ptom uses plain HTTP for add-on downloads in path http://raw.githubusercontent.com/ptom98/PTOM/master/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2020-03-19 11:34:32.851 T:6528 WARNING: Previous line repeats 2 times.
2020-03-19 11:34:32.851 T:6528   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
2020-03-19 11:34:35.451 T:14792   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "D:\Program Files\Kodi\portable_data\addons\plugin.video.wonderfulsubs\default.py", line 292, in <module>
                                                router_process(control.get_plugin_url(), control.get_plugin_params())
                                              File "D:\Program Files\Kodi\portable_data\addons\plugin.video.wonderfulsubs\resources\lib\ui\router.py", line 68, in router_process
                                                return route_obj.func(payload, params)
                                              File "D:\Program Files\Kodi\portable_data\addons\plugin.video.wonderfulsubs\default.py", line 230, in SEARCH_PAGES
                                                return control.draw_items(_BROWSER.search_site(query, int(page)), draw_cm=draw_cm)
                                              File "D:\Program Files\Kodi\portable_data\addons\plugin.video.wonderfulsubs\resources\lib\WonderfulSubsBrowser.py", line 289, in search_site
                                                return self._process_anime_view(url, data, "search/%s/%%d" % search_string, page)
                                              File "D:\Program Files\Kodi\portable_data\addons\plugin.video.wonderfulsubs\resources\lib\WonderfulSubsBrowser.py", line 107, in _process_anime_view
                                                json_resp = self._json_request(url, data)
                                              File "D:\Program Files\Kodi\portable_data\addons\plugin.video.wonderfulsubs\resources\lib\WonderfulSubsBrowser.py", line 98, in _json_request
                                                response = json.loads(self._get_request(url, data))
                                              File "D:\Program Files\Kodi\system\python\Lib\json\__init__.py", line 339, in loads
                                                return _default_decoder.decode(s)
                                              File "D:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 364, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "D:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 382, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
2020-03-19 11:34:35.480 T:10008   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.wonderfulsubs/search/code geass/1
2020-03-19 11:34:35.485 T:6528   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.wonderfulsubs/search/code geass/1) failed

**Comment by nalch** [comment]
Wonderful subs migrated to another api version and needs a login for accessing the content it seems.
I created a #134 for those changes so it works again.

So now we have to wait for a maintainer (@DxCx) to check the PR and release a new version or use the pr locally :)

**Comment by jryan15** [comment]
Thanks so much for the branch!  In this time of social distancing, it is really nice to be able to log more anime watching time :-)
