### ISSUE TITLE
Problem with Kodi Favourites

### ISSUE THREAD

**Issue by lpuglia** [DxCx/plugin.video.wonderfulsubs#144]
Hello, I just intalled the addon from repoitory (latest version) and it works perfectly but i have a problem: I tried to save an entry (One Piece in this case) as Favourite for the Favourite tab of Kodi main menu. The thumbnail is displayed correctly but It doesn't work when selected. i just get a generic error popup and this error in the log:

```
2020-05-16 10:57:40.685 T:2383409360   ERROR: /home/pi/.kodi/addons/plugin.video.wonderfulsubs/resources/lib/WonderfulSubsBrowser.py:131: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
                                              return response.encode("utf-8") == u"Forbidden"
2020-05-16 10:57:41.227 T:2383409360   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ''
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.wonderfulsubs/default.py", line 332, in <module>
                                                router_process(control.get_plugin_url(), control.get_plugin_params())
                                              File "/home/pi/.kodi/addons/plugin.video.wonderfulsubs/resources/lib/ui/router.py", line 68, in router_process
                                                return route_obj.func(payload, params)
                                              File "/home/pi/.kodi/addons/plugin.video.wonderfulsubs/default.py", line 157, in ANIMES_PAGE
                                                episodes = _BROWSER.get_anime_episodes(anime_url, is_dubbed, season, desc_order)
                                              File "/home/pi/.kodi/addons/plugin.video.wonderfulsubs/resources/lib/WonderfulSubsBrowser.py", line 388, in get_anime_episodes
                                                return self._get_anime_episodes(info, season, desc_order)
                                              File "/home/pi/.kodi/addons/plugin.video.wonderfulsubs/resources/lib/WonderfulSubsBrowser.py", line 303, in _get_anime_episodes
                                                season = info["seasons"][season]
                                            KeyError: ''
                                            -->End of Python script error report<--
2020-05-16 10:57:41.356 T:2567495888   ERROR: GetDirectory - Error getting plugin://plugin.video.wonderfulsubs/animes/onepiece/sub/
2020-05-16 10:57:41.368 T:2972970080   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.wonderfulsubs/animes/onepiece/sub/) failed
```

Is it a problem with my installation or is it a feature not supported?

### System info

HW: Raspberry Pi 4
Kernel: Linux raspberrypi 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux
Kodi: 18.6 Git:20200310-283bece277 Media Center Kodi

**Comment by DxCx** [comment]
Hmm.. feature is supported.

Logs shows it is related to login, have you setup login user/password at settings?
Does normal browse works?

**Comment by Ichijoe2112** [comment]
The last time this Add-on saw an update. The Website in question "Wonderfulsubs"? Was under some very heavy maintenance, as that the actual Website itself was (quite factually), useless I am personally at unawares of any progress since that time. But, if the latest update was ment to have done anything, it did not do much for me.

Though that much could be on me. As I did try loading that side hack that was posted in another thread. Which also didn't quite work until I did a clean install of that addon. Which was also only Working with subbed videos. So it might be interesting  just to see if one could in fact register oneself to Wondersubs. And to see if the site has actually improved  in the last 3 months now.

I'm about ready to just accept that this Add-on (like so many others before it), has met it's natural fate.

**Comment by Ichijoe2112** [comment]
Well I just poked my proboscis in, and well the Site is still under "construction" you can not use your login or create a new one, without some 404 error. Of course nothing on this site actually has anything to display to you. So im confident that the Add-on (I.e. The Frintend), is working as expected. The Backend? i.e. Wondersubs. Not so much. So if that is down then so to with this Add-on.

More's a pitty too with what Shield Hero season 2 incoming.
